CLASS ZSP_BP_MITARBEITER DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF ZSP_R_MITARBEITER.
    PROTECTED SECTION.

    PRIVATE SECTION.
endclass.

class ZSP_BP_MITARBEITER IMPLEMENTATION.

endclass.

